{{-- resources/views/mail/admin-request-notification.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New {{ ucfirst($type) }} Request</title>
    <style>
        /* Embedded CSS for email clients */
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f7fa; margin: 0; padding: 0; -webkit-font-smoothing: antialiased; }
        .wrapper { width: 100%; table-layout: fixed; background-color: #f4f7fa; padding-bottom: 40px; }
        .container { max-width: 650px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-top: 20px; }
        .header { background-color: #2c3e50; color: #ffffff; padding: 20px; text-align: center; border-bottom: 4px solid #e74c3c; }
        .header h1 { margin: 0; font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
        .content { padding: 30px; color: #333333; line-height: 1.6; font-size: 15px; }
        .intro { font-size: 18px; font-weight: bold; margin-bottom: 20px; color: #2c3e50; padding-bottom: 10px; border-bottom: 1px solid #eeeeee; }
        
        /* Data Table Styles */
        .data-table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 14px; }
        .data-table th, .data-table td { padding: 12px 15px; border: 1px solid #e2e8f0; vertical-align: top; }
        .data-table .key-col { width: 35%; background-color: #f8fafc; font-weight: bold; color: #475569; text-transform: capitalize; }
        .data-table .val-col { width: 65%; color: #1e293b; word-break: break-word; }
        
        .footer { background-color: #f8fafc; color: #64748b; padding: 15px 20px; font-size: 12px; text-align: center; border-top: 1px solid #e2e8f0; }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <div class="header">
                <h1>Admin System Alert</h1>
            </div>

            <div class="content">
                <div class="intro">
                    New {{ ucfirst($type) }} request received
                </div>

                <p>A new request has been submitted to the system. Below are the payload details:</p>

                <table class="data-table">
                    <tbody>
                        @foreach($payload as $key => $value)
                            @php
                                // Handle arrays, objects, or standard strings safely
                                if (is_array($value) || is_object($value)) {
                                    $displayValue = json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
                                } else {
                                    $displayValue = (string) $value;
                                }
                                
                                // Format the key to look cleaner (e.g. 'first_name' -> 'First name')
                                $displayKey = str_replace('_', ' ', $key);
                            @endphp
                            <tr>
                                <td class="key-col">{{ $displayKey }}</td>
                                <td class="val-col">
                                    {{-- Use <pre> tag for JSON arrays to keep them readable --}}
                                    @if(is_array($value) || is_object($value))
                                        <pre style="margin: 0; font-family: monospace; font-size: 12px;">{{ $displayValue }}</pre>
                                    @else
                                        {{ $displayValue }}
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="footer">
                <p style="margin: 0;">This is an automated system notification generated by the Global Trading application.</p>
                <p style="margin: 5px 0 0 0;">Timestamp: {{ now()->toDayDateTimeString() }}</p>
            </div>
        </div>
    </div>
</body>
</html>